
_script = jedi.Script(__code)
_result = None
_items = _script.help(__line, __column)

if not _items:
    _items = _script.infer(__line, __column)

_api_attribute_docs = {
    'Workspace.metadata': 'metadata: pd.DataFrame\n\nA typed pandas DataFrame containing one row per sample. Group and Sample are read-only identity columns; all other columns are sample metadata. This is a copy; use apply_metadata(dataframe) to replace workspace metadata with the edited table.',
    'Workspace.groupings': 'groupings: list[Grouping]\n\nThe grouping collection in the current workspace. Use workspace[group_name] to retrieve one grouping by name.',
    'Grouping.name': 'name: str\n\nThe grouping name.',
    'Grouping.samples': 'samples: list[Sample]\n\nSamples contained in this grouping.',
    'Grouping.strategies': 'strategies: Strategy\n\nThe root strategy node for grouping-level gates and statistics.',
    'Grouping.compensations': 'compensations: dict[str, Compensation]\n\nRegistered compensation candidates keyed by compensation name.',
    'Grouping.current_compensation': 'current_compensation: str\n\nName of the applied compensation, or an empty string when no compensation is applied.',
    'Grouping.channels': 'channels: list[str]\n\nOrdered channel names shared by compatible samples in this grouping.',
    'Sample.name': 'name: str\n\nThe sample name.',
    'Sample.channels': 'channels: list[str]\n\nOrdered channel names in this sample.',
    'Sample.embeddings': 'embeddings: list[str]\n\nNames of sample-level embedding arrays available for plotting and downstream analysis.',
    'Sample.matrix': 'matrix: np.ndarray\n\nRaw event matrix as a NumPy copy. Rows are events and columns follow sample.channels.',
    'Sample.embedding_matrix': 'embedding_matrix: np.ndarray\n\nA NumPy copy of all sample embeddings stacked as columns in sample.embeddings order.',
    'Sample.populations': 'populations: dict[str, Population]\n\nPopulation results keyed by population key.',
    'Sample.strategy': 'strategy: Strategy\n\nThe root strategy for this sample grouping.',
    'Sample.population_keys': 'population_keys: list[str]\n\nAvailable population keys for this sample.',
    'Population.mask': 'mask: np.ndarray\n\nA boolean sample-wide mask. True marks events that belong to this population.',
    'Population.populations': 'populations: dict[str, Population]\n\nChild populations keyed by population key.',
    'Population.strategy': 'strategy: Strategy\n\nThe strategy node that produced this population.',
    'Population.population_keys': 'population_keys: list[str]\n\nAvailable child population keys.',
    'Strategy.name': 'name: str\n\nThe grouping or gate strategy name.',
    'Strategy.statistics': 'statistics: list[StatisticDefinition]\n\nStatistics attached to this strategy node.',
    'Strategy.population_keys': 'population_keys: list[str]\n\nPopulation keys generated by child gates.',
    'Strategy.has_multiple_populations': 'has_multiple_populations: bool\n\nTrue when this strategy has more than one population region.',
    'StatisticDefinition.kind': 'kind: str\n\nNative statistic kind name, or Python for source-backed Python statistics.',
    'Compensation.name': 'name: str\n\nThe compensation name.',
    'Compensation.channels': 'channels: list[str]\n\nOrdered channel names covered by the compensation matrix.',
    'Compensation.matrix': 'matrix: np.ndarray\n\nThe compensation matrix as a NumPy copy.'
}

_api_class_names = {'Workspace', 'Grouping', 'Sample', 'Population', 'Strategy', 'StatisticDefinition', 'Compensation'}

def _definition_class(_item):
    try:
        _position = _item.get_definition_start_position()
    except Exception:
        return ''
    if not _position:
        return ''
    _line = _position[0]
    _lines = __code.splitlines()
    _index = min(max(_line - 1, 0), len(_lines) - 1)
    while _index >= 0:
        _text = _lines[_index]
        if _text.startswith('class '):
            return _text.split('class ', 1)[1].split(':', 1)[0].split('(', 1)[0].strip()
        _index -= 1
    return ''

def _api_attribute_doc(_item):
    _name = getattr(_item, 'name', '') or ''
    if not _name:
        return ''
    _class_name = _definition_class(_item)
    if not _class_name:
        return ''
    return _api_attribute_docs.get(f'{_class_name}.{_name}', '')

def _best_inferred_doc(_item):
    try:
        _inferred = _item.infer() if hasattr(_item, 'infer') else []
    except Exception:
        _inferred = []
    for _inferred_item in _inferred:
        _name = getattr(_inferred_item, 'name', '') or ''
        try:
            _doc = _inferred_item.docstring(raw=True) if hasattr(_inferred_item, 'docstring') else ''
        except Exception:
            _doc = ''
        if _doc and (_name in _api_class_names or not _doc.startswith(_name + ':')):
            return _doc
    return ''

def _doc_blocks(_doc):
    if not _doc:
        return []
    try:
        import docstring_parser as _docstring_parser
        _parsed = _docstring_parser.parse(_doc)
        _blocks = []
        if _parsed.short_description:
            _blocks.append({'kind': 'paragraph', 'text': _parsed.short_description})
        if _parsed.long_description:
            _blocks.append({'kind': 'paragraph', 'text': _parsed.long_description})
        _params = []
        for _param in getattr(_parsed, 'params', []) or []:
            _name = getattr(_param, 'arg_name', '') or ''
            _type_name = getattr(_param, 'type_name', '') or ''
            _description = getattr(_param, 'description', '') or ''
            if _name or _description:
                _label = _name if not _type_name else f'{_name} : {_type_name}'
                _params.append({'label': _label, 'text': _description})
        if _params:
            _blocks.append({'kind': 'section', 'title': 'Parameters'})
            _blocks.append({'kind': 'list', 'items': _params})
        _returns = getattr(_parsed, 'returns', None)
        if _returns:
            _return_type = getattr(_returns, 'type_name', '') or ''
            _return_description = getattr(_returns, 'description', '') or ''
            _return_text = _return_description if not _return_type else f'{_return_type}. {_return_description}'.strip()
            if _return_text:
                _blocks.append({'kind': 'section', 'title': 'Returns'})
                _blocks.append({'kind': 'paragraph', 'text': _return_text})
        _raises = []
        for _raise in getattr(_parsed, 'raises', []) or []:
            _type_name = getattr(_raise, 'type_name', '') or ''
            _description = getattr(_raise, 'description', '') or ''
            if _type_name or _description:
                _raises.append({'label': _type_name, 'text': _description})
        if _raises:
            _blocks.append({'kind': 'section', 'title': 'Raises'})
            _blocks.append({'kind': 'list', 'items': _raises})
        for _example in getattr(_parsed, 'examples', []) or []:
            _description = getattr(_example, 'description', '') or ''
            _snippet = getattr(_example, 'snippet', '') or ''
            if _description:
                _blocks.append({'kind': 'paragraph', 'text': _description})
            if _snippet:
                _blocks.append({'kind': 'code', 'text': _snippet})
        return _blocks if _blocks else [{'kind': 'raw', 'text': _doc}]
    except Exception:
        return [{'kind': 'raw', 'text': _doc}]

if _items:
    _item = _items[0]
    _type = getattr(_item, 'type', '')
    _description = getattr(_item, 'description', '')
    _doc = _item.docstring(raw=True) if hasattr(_item, 'docstring') else ''
    _api_doc = _api_attribute_doc(_item)
    if _api_doc:
        _doc = _api_doc
    elif not _doc or _type in ('statement', 'instance', 'param'):
        _inferred_doc = _best_inferred_doc(_item)
        if _inferred_doc:
            _doc = _inferred_doc
    _signature = ''
    if _type in ('function', 'method', 'class'):
        try:
            _signatures = _item.get_signatures() if hasattr(_item, 'get_signatures') else []
            if _signatures:
                _signature = _signatures[0].to_string()
        except Exception:
            _signature = ''
    _result = {
        'type': _type,
        'description': _description,
        'signature': _signature,
        'docstring': _doc,
        'docblocks': _doc_blocks(_doc)
    }

import json as _json
_result_json = _json.dumps(_result)
