
from __future__ import annotations
from typing import Callable
import numpy as np
import pandas as pd

class Compensation:
    '''
    A compensation matrix registered on a grouping.

    Attributes
    ==========
    name: readonly str
        The compensation name.

    channels: readonly list[str]
        The ordered channel names covered by the matrix.

    matrix: readonly np.ndarray
        A copy of the compensation matrix as a two-dimensional float array.
    '''
    name: str
    channels: list[str]
    matrix: np.ndarray

class StatisticDefinition:
    '''
    A statistic attached to a grouping or gate strategy.

    Attributes
    ==========
    kind: readonly str
        Native statistic kind name, or "Python" for source-backed Python statistics.
    '''
    kind: str
    def is_python(self) -> bool: ...
    def get_method(self) -> str: ...
    def set_method(self, source: str, callable_name: str = "entry", display_name: str | None = None, parameters: np.ndarray | None = None): 
        '''
        Replaces this statistic with a Python-backed implementation.

        Parameters
        ==========
        source: str
            Python source text defining the callable.
            Where function signature should be:
            >>> def entry(matrix: np.ndarray, channels: list[str], parameters: np.ndarray) -> np.ndarray:

        callable_name: str, default "entry"
            Name of the callable inside source.

        display_name: str | None, default None
            Optional name shown in the statistics table.

        parameters: np.ndarray | None, default None
            Optional numeric parameter vector passed to the callable.
        '''
        ...

class Population:
    '''
    A population result for a sample and gate region.

    Attributes
    ==========
    mask: readonly np.ndarray
        Boolean sample-wide mask. True values mark events in this population.

    populations: readonly dict[str, Population]
        Child populations keyed by population key.

    strategy: readonly Strategy
        Strategy node that produced this population.

    population_keys: readonly list[str]
        Available child population keys.
    '''
    mask: np.ndarray
    populations: dict[str, "Population"]
    strategy: "Strategy"
    population_keys: list[str]
    def get_compensated_matrix(self) -> np.ndarray: 
        '''
        Returns compensated event rows selected by this population as a NumPy copy.
        '''
        ...

    def set_embedding(self, name: str, value: np.ndarray): 
        '''
        Writes a one-dimensional embedding into the owning sample for this population.

        value must be a one-dimensional NumPy array of floats or strings. Float
        arrays are stored as floating-point embeddings. String arrays are stored
        as categorical integer embeddings with category text metadata.

        value may contain exactly one value per selected event, or one value per
        event in the full sample. Only masked events are written; non-population
        events keep existing values or become NaN for a new embedding.
        '''
        ...

    def __getitem__(self, population_key: str) -> "Population": 
        '''
        Returns a child population by key, equivalent to population[population_key].
        '''
        ...

class Sample:
    '''
    A flow sample inside a grouping.

    Attributes
    ==========
    name: readonly str
        Sample name.

    channels: readonly list[str]
        Ordered channel names.

    embeddings: readonly list[str]
        Names of sample-level embedding arrays.

    matrix: readonly np.ndarray
        Raw event matrix as a NumPy copy.

    embedding_matrix: readonly np.ndarray
        Matrix containing all embeddings as columns.

    populations: readonly dict[str, Population]
        Populations keyed by population key.

    strategy: readonly Strategy
        Root strategy for this sample's grouping.
    '''
    name: str
    channels: list[str]
    embeddings: list[str]
    matrix: np.ndarray
    embedding_matrix: np.ndarray
    populations: dict[str, Population]
    strategy: "Strategy"
    population_keys: list[str]
    def get_compensated_matrix(self) -> np.ndarray: 
        '''
        Returns the compensated event matrix as a NumPy copy.
        '''
        ...
    def __getitem__(self, population_key: str) -> Population: 
        '''
        Returns a population by key, equivalent to sample[population_key].
        '''
        ...

class Strategy:
    '''
    A grouping or gate strategy node. Defining gates and statistics mutates the
    workspace tree immediately and recalculates the owning grouping.

    Attributes
    ==========
    name: readonly str
        Strategy or gate name.

    statistics: readonly list[StatisticDefinition]
        Statistics attached to this strategy node.

    population_keys: readonly list[str]
        Population keys generated by child gates.

    has_multiple_populations: readonly bool
        True for gates that expose multiple regions.
    '''
    name: str
    statistics: list[StatisticDefinition]
    population_keys: list[str]
    has_multiple_populations: bool
    def children(self, population_key: str = "default") -> list["Strategy"]: ...
    def get_population(self, sample: Sample) -> Population: ...
    def get_statistics(self, sample: Sample, statistic: StatisticDefinition) -> np.ndarray: ...
    
    def define_statistics(self, kind: str, channel: str = "") -> StatisticDefinition: 
        '''
        Adds a native statistic. kind is a StatisticKind name such as Mean,
        Median, NumberOfEvents, FrequencyOfParent, or FrequencyOfAll.
        '''
        ...
    def define_statistics_python(self, source: str, callable_name: str = "statistic", display_name: str | None = None, parameters: np.ndarray | None = None) -> StatisticDefinition: 
        '''
        Adds a Python statistic whose callable receives
        (matrix: np.ndarray, channels: list[str], parameters: np.ndarray).
        '''
        ...
    def define_gate_polygon(self, name: str, population_key: str, channel1: str, channel2: str, vertices: np.ndarray) -> "Strategy": 
        '''Adds a polygon gate. vertices is an N x 2 array.'''
        ...
    def define_gate_rectangle(self, name: str, population_key: str, channel1: str, channel2: str, rectangle: np.ndarray) -> "Strategy": 
        '''Adds a rectangle gate from a two-row or corner-style coordinate array.'''
        ...
    def define_gate_quadrant(self, name: str, population_key: str, channel1: str, channel2: str, center: np.ndarray) -> "Strategy": 
        '''Adds a quadrant gate using center coordinates.'''
        ...
    def define_gate_curly(self, name: str, population_key: str, channel1: str, channel2: str, center: np.ndarray) -> "Strategy": 
        '''Adds a curly quadrant gate using center coordinates.'''
        ...
    def define_gate_offset(self, name: str, population_key: str, channel1: str, channel2: str, positions: np.ndarray) -> "Strategy": 
        '''Adds an offset quadrant gate using offset positions.'''
        ...
    def define_gate_threshold(self, name: str, population_key: str, channel1: str, position: np.ndarray) -> "Strategy": 
        '''Adds a one-dimensional threshold gate.'''
        ...
    def define_gate_range(self, name: str, population_key: str, channel1: str, positions: np.ndarray) -> "Strategy": 
        '''Adds a one-dimensional range gate.'''
        ...
    def define_gate_overlap(self, name: str, population_key: str, gate2: str, population2: str) -> "Strategy": 
        '''Adds a boolean overlap gate against another gate population.'''
        ...
    def define_gate_exclude(self, name: str, population_key: str, gate2: str, population2: str) -> "Strategy": 
        '''Adds a boolean exclusion gate against another gate population.'''
        ...
    def define_gate_merge(self, name: str, population_key: str, gate2: str, population2: str) -> "Strategy": 
        '''Adds a boolean merge gate against another gate population.'''
        ...

class Grouping:
    '''
    A named collection of compatible samples, gates, statistics, and compensation.

    Attributes
    ==========
    name: readonly str
        Grouping name.

    samples: readonly list[Sample]
        Samples in this grouping.

    strategies: readonly Strategy
        Root strategy for gates and grouping-level statistics.

    compensations: readonly dict[str, Compensation]
        Compensation candidates keyed by name.

    current_compensation: readonly str
        Name of the applied compensation, or an empty string.

    channels: readonly list[str]
        Ordered channel names for compatible samples.
    '''
    name: str
    samples: list[Sample]
    strategies: Strategy
    compensations: dict[str, Compensation]
    current_compensation: str
    channels: list[str]
    def add_fcs(self, filename: str) -> Sample: 
        '''Reads an FCS file, validates compatibility, appends it, and recalculates.'''
        ...
    def can_accept_fcs(self, filename: str) -> bool: 
        '''Returns whether an FCS file is compatible with this grouping.'''
        ...
    def set_compensation(self, key: str) -> Compensation: 
        '''Applies a registered compensation candidate and recalculates samples.'''
        ...
    def create_compensation(self, key: str, channels: list[str], matrix: np.ndarray) -> Compensation: 
        '''Registers a compensation matrix for the supplied channel order.'''
        ...
    def __getitem__(self, sample: str) -> Sample: 
        '''Returns a sample by name, equivalent to grouping[sample].'''
        ...

class Workspace:
    '''
    The main workspace object representing the currently opened workspace in the application.
    All groupings, samples, and further properties, and metadata table are accessible through this object.

    Attributes
    ==========
    metadata: readonly pd.DataFrame
        A typed pandas DataFrame containing the workspace metadata table. Group and Sample are
        read-only identity columns; apply_metadata(dataframe) ignores them as metadata values.
    
    groupings: readonly list[Grouping]
        A list of groupings in the workspace. Each grouping represents a collection of samples that are 
        analyzed together. A grouping can have multiple samples.

    integration_jobs: readonly list[IntegrationJob]
        Integration jobs with source, logicle-normalized, integrated matrices, row maps, features,
        and batch ids for downstream Python macros.
    '''

    metadata: pd.DataFrame
    groupings: list[Grouping]
    integration_jobs: list
    def add_grouping(self, name: str) -> Grouping: ...
    def apply_metadata(self, dataframe: pd.DataFrame): 
        '''
        Replaces workspace metadata with the given DataFrame. Group and Sample identify rows and are
        ignored as metadata fields; all other columns become typed metadata columns.
        '''
        ...
    def __getitem__(self, grouping: str) -> Grouping: ...

workspace: Workspace
'''
Main workspace instance
'''

def log(content): 
    '''
    Print a debug log content to the application debug console.
    Script engineer would inspect intermediate result using the console.
    By default, end users may not see the contents in it. If it is required to alert the user,
    it is better to use ``msgbox(title, content)`` instead.
    '''
    ...

def msgbox(title: str, content: str): 
    '''
    Push a model dialog message box

    Parameters
    ==========
    title: str
        Message box title
    
    content: str
        Plain text message box content
    '''
    ...
