
from __future__ import annotations
from typing import Callable, Literal
import numpy as np
import pandas as pd

class Compensation:
    '''
    A compensation matrix registered on a grouping.

    Attributes
    ==========
    name: readonly str
        The compensation name.

    channels: readonly list[str]
        The ordered channel names covered by the matrix.

    matrix: readonly np.ndarray
        A copy of the compensation matrix as a two-dimensional float array.
    '''
    name: str
    channels: list[str]
    matrix: np.ndarray

class StatisticDefinition:
    '''
    A statistic attached to a grouping or gate strategy.

    Attributes
    ==========
    kind: readonly str
        Native statistic kind name, or "Python" for source-backed Python statistics.
    '''
    kind: str
    def is_python(self) -> bool: ...
    def get_method(self) -> str: ...
    def set_method(self, source: str, callable_name: str = "entry", display_name: str | None = None, parameters: np.ndarray | None = None): 
        '''
        Replaces this statistic with a Python-backed implementation.

        Parameters
        ==========
        source: str
            Python source text defining the callable.
            Where function signature should be:
            >>> def entry(matrix: np.ndarray, channels: list[str], parameters: np.ndarray) -> np.ndarray:

        callable_name: str, default "entry"
            Name of the callable inside source.

        display_name: str | None, default None
            Optional name shown in the statistics table.

        parameters: np.ndarray | None, default None
            Optional numeric parameter vector passed to the callable.
        '''
        ...

class Population:
    '''
    A population result for a sample and gate region.

    Attributes
    ==========
    mask: readonly np.ndarray
        Boolean sample-wide mask. True values mark events in this population.

    populations: readonly dict[str, Population]
        Child populations keyed by population key.

    strategy: readonly Strategy
        Strategy node that produced this population.

    population_keys: readonly list[str]
        Available child population keys.

    compensated_matrix: readonly np.ndarray
        Compensated event matrix as a NumPy readonly array.
    '''
    mask: np.ndarray
    populations: dict[str, "Population"]
    strategy: "Strategy"
    population_keys: list[str]
    compensated_matrix: np.ndarray

    def set_embedding(self, name: str, value: np.ndarray): 
        '''
        Writes a one-dimensional embedding into the owning sample for this population.

        value must be a one-dimensional NumPy array of floats or strings. Float
        arrays are stored as floating-point embeddings. String arrays are stored
        as categorical integer embeddings with category text metadata.

        value may contain exactly one value per selected event, or one value per
        event in the full sample. Only masked events are written; non-population
        events keep existing values or become NaN for a new embedding.
        '''
        ...

    def __getitem__(self, population_key: str) -> "Population": 
        '''
        Returns a child population by key, equivalent to population[population_key].
        '''
        ...

class Sample:
    '''
    A flow sample inside a grouping.

    Attributes
    ==========
    name: readonly str
        Sample name.

    channels: readonly list[str]
        Ordered channel names.

    embeddings: readonly list[str]
        Names of sample-level embedding arrays.

    matrix: readonly np.ndarray
        Raw event matrix as a NumPy readonly array.

    embedding_matrix: readonly np.ndarray
        Matrix containing all embeddings as columns.

    compensated_matrix: readonly np.ndarray
        Compensated event matrix as a NumPy readonly array.

    populations: readonly dict[str, Population]
        Populations keyed by population key.

    strategy: readonly Strategy
        Root strategy for this sample's grouping.
    '''
    name: str
    channels: list[str]
    embeddings: list[str]
    matrix: np.ndarray
    embedding_matrix: np.ndarray
    populations: dict[str, Population]
    strategy: "Strategy"
    population_keys: list[str]
    compensated_matrix: np.ndarray
        
    def __getitem__(self, population_key: str) -> Population: 
        '''
        Returns a population by key, equivalent to sample[population_key].
        '''
        ...

class Strategy:
    '''
    A grouping or gate strategy node. Defining gates and statistics mutates the
    workspace tree immediately and recalculates the owning grouping.

    Attributes
    ==========
    name: readonly str
        Strategy or gate name.

    statistics: readonly list[StatisticDefinition]
        Statistics attached to this strategy node.

    population_keys: readonly list[str]
        Population keys generated by child gates.

    has_multiple_populations: readonly bool
        True for gates that expose multiple regions.
    '''
    name: str
    statistics: list[StatisticDefinition]
    population_keys: list[str]
    has_multiple_populations: bool
    def children(self, population_key: str = "default") -> list["Strategy"]: ...
    def get_population(self, sample: Sample) -> Population: ...
    def get_statistics(self, sample: Sample, statistic: StatisticDefinition) -> np.ndarray: ...
    
    def define_statistics(self, kind: str, channel: str) -> StatisticDefinition: 
        '''
        Adds a native statistic. kind is a StatisticKind name such as Mean,
        Median, NumberOfEvents, FrequencyOfParent, or FrequencyOfAll.
        '''
        ...
    def define_statistics_python(self, source: str, callable_name: str = "entry", display_name: str | None = None, parameters: np.ndarray | None = None) -> StatisticDefinition: 
        '''
        Adds a Python statistic whose callable receives
        (matrix: np.ndarray, channels: list[str], parameters: np.ndarray).
        '''
        ...
    def define_gate_polygon(self, name: str, population_key: str, channel1: str, channel2: str, vertices: np.ndarray) -> "Strategy": 
        '''Adds a polygon gate. vertices is an N x 2 array.'''
        ...
    def define_gate_rectangle(self, name: str, population_key: str, channel1: str, channel2: str, rectangle: np.ndarray) -> "Strategy": 
        '''Adds a rectangle gate from a two-row or corner-style coordinate array.'''
        ...
    def define_gate_quadrant(self, name: str, population_key: str, channel1: str, channel2: str, center: np.ndarray) -> "Strategy": 
        '''Adds a quadrant gate using center coordinates.'''
        ...
    def define_gate_curly(self, name: str, population_key: str, channel1: str, channel2: str, center: np.ndarray) -> "Strategy": 
        '''Adds a curly quadrant gate using center coordinates.'''
        ...
    def define_gate_offset(self, name: str, population_key: str, channel1: str, channel2: str, positions: np.ndarray) -> "Strategy": 
        '''Adds an offset quadrant gate using offset positions.'''
        ...
    def define_gate_threshold(self, name: str, population_key: str, channel1: str, position: np.ndarray) -> "Strategy": 
        '''Adds a one-dimensional threshold gate.'''
        ...
    def define_gate_range(self, name: str, population_key: str, channel1: str, positions: np.ndarray) -> "Strategy": 
        '''Adds a one-dimensional range gate.'''
        ...
    def define_gate_overlap(self, name: str, population_key: str, gate2: str, population2: str) -> "Strategy": 
        '''Adds a boolean overlap gate against another gate population.'''
        ...
    def define_gate_exclude(self, name: str, population_key: str, gate2: str, population2: str) -> "Strategy": 
        '''Adds a boolean exclusion gate against another gate population.'''
        ...
    def define_gate_merge(self, name: str, population_key: str, gate2: str, population2: str) -> "Strategy": 
        '''Adds a boolean merge gate against another gate population.'''
        ...

class Grouping:
    '''
    A named collection of compatible samples, gates, statistics, and compensation.

    Attributes
    ==========
    name: readonly str
        Grouping name.

    samples: readonly list[Sample]
        Samples in this grouping.

    strategies: readonly Strategy
        Root strategy for gates and grouping-level statistics.

    compensations: readonly dict[str, Compensation]
        Compensation candidates keyed by name.

    current_compensation: readonly str
        Name of the applied compensation, or an empty string.

    channels: readonly list[str]
        Ordered channel names for compatible samples.
    '''
    name: str
    samples: list[Sample]
    strategies: Strategy
    compensations: dict[str, Compensation]
    current_compensation: str
    channels: list[str]
    def add_fcs(self, filename: str) -> Sample: 
        '''Reads an FCS file, validates compatibility, appends it, and recalculates.'''
        ...
    def can_accept_fcs(self, filename: str) -> bool: 
        '''Returns whether an FCS file is compatible with this grouping.'''
        ...
    def set_compensation(self, key: str) -> Compensation: 
        '''Applies a registered compensation candidate and recalculates samples.'''
        ...
    def create_compensation(self, key: str, channels: list[str], matrix: np.ndarray) -> Compensation: 
        '''Registers a compensation matrix for the supplied channel order.'''
        ...
    def __getitem__(self, sample: str) -> Sample: 
        '''Returns a sample by name, equivalent to grouping[sample].'''
        ...

class ViewOptions:
    '''
    Axis/view transformation settings for one channel or embedding.
    '''
    min: float
    max: float
    t: float
    w: float
    m: float
    a: float

class PlatformPopulation:
    group: str
    sample: str
    name: str
    population: str
    group_id: str
    sample_id: str
    gate_id: str
    region: str
    selected: bool

class Platform:
    '''
    Base platform wrapper. Names intentionally match the C# Platform model.
    '''
    name: str
    populations: list[PlatformPopulation]
    channels: list[str]
    matrix: np.ndarray
    compensated: np.ndarray
    transformations: dict[str, ViewOptions]
    transformed: np.ndarray
    series: dict[str, object]
    models: dict[str, object]
    components: dict[str, list[object]]
    result: dict[str, object]
    parameters: dict[str, object]
    has_graphics: bool
    has_data_table: bool
    row_map: pd.DataFrame

    def sample_metadata(self, sample_name: str, column_name: str) -> str:
        '''Returns a workspace metadata value for a sample, or an empty string if unavailable.'''
        ...

    def set_embedding(self, name: str, value: np.ndarray):
        '''
        Writes one value per integration row back into the source samples as a synchronized embedding.

        Numeric arrays create floating-point embeddings. String arrays create categorical embeddings.
        '''
        ...

    def clear_results(self):
        '''Clears platform result tables, plot series, and statistics before writing new results.'''
        ...

    def set_result_table(self, key: str, title: str, columns: list[str], rows: list[list[str]]):
        '''Writes a named table result that can be rendered in layouts.'''
        ...

    def set_plot_series(self, key: str, title: str, x: np.ndarray, y: np.ndarray, x_label: str = "", y_label: str = "", source_id: int = -1, role: str = "observed"):
        '''Writes a named x/y result. role is observed, fit, or component.'''
        ...

    def set_fit_curve(self, key: str, title: str, kind: str, source_id: int, parameters: list[float], normalizer: float = 1.0, x_label: str = "", y_label: str = "", role: str = "fit"):
        '''Writes a parameterized fitted curve. kind is Gaussian, GaussianSum, CellCycleSum, Linear, or Exponential; role is fit or component.'''
        ...

    def add_component_gamma(self, key: str, alpha: float, beta: float, amplitude: float):
        ...

    def add_component_normal(self, key: str, mu: float, sigma: float, amplitude: float):
        ...

    def add_component_exponential(self, key: str, slope: float, expn: float, intercept: float):
        ...

    def set_fit_addition(self, key: str, models: list[str], weights: list[float], intercept: float = 0):
        ...

    def set_statistic(self, name: str, value):
        '''Writes a named platform statistic shown in linked layout statistic tables.'''
        ...

class UnivariatePlatform(Platform):
    major: str
    histogram: np.ndarray
    smoothed: np.ndarray
    smoothing_window: int
    enable_smoothing: bool

class MultivariatePlatform(Platform):
    normalized: np.ndarray

class Workspace:
    '''
    The main workspace object representing the currently opened workspace in the application.
    All groupings, samples, and further properties, and metadata table are accessible through this object.

    Attributes
    ==========
    metadata: readonly pd.DataFrame
        A typed pandas DataFrame containing the workspace metadata table. Group and Sample are
        read-only identity columns; apply_metadata(dataframe) ignores them as metadata values.
    
    groupings: readonly list[Grouping]
        A list of groupings in the workspace. Each grouping represents a collection of samples that are 
        analyzed together. A grouping can have multiple samples.

    platforms: readonly dict[str, Platform]
        Prepared platforms keyed by platform name.

    storage: dict
        Workspace-scoped Python dictionary shared by all script runs. It is kept in memory only
        and cleared when the workspace is closed or replaced.
    '''

    metadata: pd.DataFrame
    groupings: list[Grouping]
    platforms: dict[str, Platform]
    storage: dict
    
    def add_grouping(self, name: str) -> Grouping: ...
    def apply_metadata(self, dataframe: pd.DataFrame): 
        '''
        Replaces workspace metadata with the given DataFrame. Group and Sample identify rows and are
        ignored as metadata fields; all other columns become typed metadata columns.
        '''
        ...
    def __getitem__(self, grouping: str) -> Grouping: ...

workspace: Workspace

platform: Platform
'''
Current platform when running an embedded platform resource script.
'''

class Application:
    '''
    Application-level utilities for script interaction. The application object is available in
    macro, integration, and Python statistic scripts.
    '''

    def log(self, content):
        '''
        Writes an info-level message to the current task log.
        '''
        ...

    def warning(self, content):
        '''
        Writes a warning-level message, asks whether to proceed, and cancels the run if rejected.
        '''
        ...

    def error(self, content):
        '''
        Writes an error-level message and interrupts the current run.
        '''
        ...

    def msgbox(self, title: str, content: str, buttons: Literal["ok", "ok-cancel", "proceed-cancel", "yes-no-cancel"] = "ok") -> str:
        '''
        Shows a modal message box and returns the selected button value.

        Returns one of "ok", "cancel", "yes", or "no", depending on the requested button set.
        '''
        ...

    def input(self, requires: list) -> list:
        '''
        Shows a modal input dialog built from requirement declarations and returns a list of
        user-selected values in the same order as the requirement list.
        '''
        ...

    def require_channel(self, name: str, default: str | list[str] | None = None, multiple: bool = False):
        '''
        Declares a channel selector requirement.
        '''
        ...

    def require_integer(self, name: str, default: int = 0, min = None, max = None):
        '''
        Declares an integer numeric input requirement.
        '''
        ...

    def require_float(self, name: str, default: float = 0.0, min = None, max = None):
        '''
        Declares a floating-point numeric input requirement.
        '''
        ...

    def require_enum(self, name: str, possible_values: list[str], default: str | None = None):
        '''
        Declares a single-choice input requirement.
        '''
        ...

    def require_option(self, name: str, default: bool):
        '''
        Declares a checkbox input requirement.
        '''
        ...

    def progress(self, percentage: float, description: str = ""):
        '''
        Updates the application status bar with deterministic script progress.
        percentage is clamped to 0..100.
        '''
        ...

application: Application
'''
Application utility instance.
'''
